/* eslint-disable */
/**
 * Generated `api` utility.
 * This is a STUB file generated to allow the build to succeed before `npx convex dev` is run.
 * When you run `npx convex dev` this file will be replaced with the real generated API.
 *
 * @module
 */

import type { ApiFromModules } from "convex/server";

// Stub — real file generated by `npx convex dev`
export declare const api: any;
export declare const internal: any;
