/* eslint-disable */
/**
 * Generated data model types.
 * This is a STUB file generated to allow the build to succeed before `npx convex dev` is run.
 * When you run `npx convex dev` this file will be replaced with the real generated types.
 *
 * @module
 */

// Stub — real file generated by `npx convex dev`
export type Id<TableName extends string = string> = string & { __tableName: TableName };
export type Doc<TableName extends string = string> = Record<string, any> & { _id: Id<TableName>; _creationTime: number };
export type TableNames = string;
export type DataModel = Record<string, any>;
