/* eslint-disable */
/**
 * Generated server utilities.
 * This is a STUB file generated to allow the build to succeed before `npx convex dev` is run.
 * When you run `npx convex dev` this file will be replaced with the real generated server utils.
 *
 * @module
 */

// Stub — real file generated by `npx convex dev`
export declare const query: any;
export declare const mutation: any;
export declare const action: any;
export declare const internalQuery: any;
export declare const internalMutation: any;
export declare const internalAction: any;
export declare const httpAction: any;
