/**
 * Cloudflare R2 Upload Hooks
 *
 * Primary upload hooks for direct-to-R2 uploads via presigned URLs.
 * Uses Convex backend to generate presigned PUT URLs, then uploads
 * directly from the browser with real progress tracking via XMLHttpRequest.
 *
 * @example
 * import { useUpload, useImageUpload } from '@/hooks/useUpload';
 *
 * // General upload
 * const { uploadMedia, uploading, progress } = useUpload('post-media');
 *
 * // Image-specific
 * const { uploadImage, uploading } = useImageUpload();
 */

import { useState } from "react";
import { useAction } from "convex/react";
import { api } from "@convex/api";
import {
  generateStorageKey,
  uploadToPresignedUrl,
  STORAGE_FOLDERS,
  isImageFile,
  isVideoFile,
  validateFileSize,
  UPLOAD_LIMITS,
  type StorageFolder,
} from "../config/storage";

// =====================================================
// TYPES
// =====================================================

/**
 * Upload result returned after a successful upload.
 */
export interface UploadResult {
  url: string;
  previewUrl: string;
  storageRef: string;
  type: string;
  name: string;
  size: number;
  mimeType: string;
  contentType?: string;
  uploadedAt?: Date;
  downloadUrl?: string;
}

/**
 * Options passed to individual upload calls.
 */
export interface UploadOptions {
  maxSizeMB?: number;
  allowedTypes?: string[];
}

/**
 * Return value of the primary useUpload hook.
 */
export interface UseUploadReturn {
  uploadMedia: (
    file: File,
    uploadPath?: string | null,
    options?: UploadOptions
  ) => Promise<UploadResult | null>;
  uploadMultiple: (
    files: FileList | File[],
    uploadPath?: string | null,
    options?: UploadOptions
  ) => Promise<UploadResult[]>;
  uploading: boolean;
  error: string | null;
  progress: number;
  isUploading: boolean;
  hasError: boolean;
  clearError: () => void;
}

// =====================================================
// PRIMARY HOOK
// =====================================================

/**
 * Primary upload hook for Cloudflare R2.
 *
 * Uses presigned URLs generated by the Convex backend for direct-to-R2
 * uploads with real progress tracking via XMLHttpRequest.upload.onprogress.
 *
 * @param defaultFolder - Default storage folder (e.g. 'post-media', 'profile-photos')
 */
export function useUpload(
  defaultFolder: StorageFolder = STORAGE_FOLDERS.POST_MEDIA
): UseUploadReturn {
  const [uploading, setUploading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [progress, setProgress] = useState<number>(0);

  const generateUploadUrlAction = useAction(api.storage.generateUploadUrl);

  /**
   * Upload a single file to R2 via presigned URL.
   */
  const uploadMedia = async (
    file: File | null,
    uploadPath: string | null = null,
    options: UploadOptions = {}
  ): Promise<UploadResult | null> => {
    if (!file) return null;

    // Validate file size (default 200MB max)
    const maxSizeMB = options.maxSizeMB ?? UPLOAD_LIMITS.MAX_FILE_SIZE_MB;
    if (!validateFileSize(file, maxSizeMB)) {
      const errorMsg = `File size exceeds ${maxSizeMB}MB limit`;
      setError(errorMsg);
      console.error(errorMsg);
      return null;
    }

    // Validate file type if specified
    if (options.allowedTypes && !options.allowedTypes.includes(file.type)) {
      const errorMsg = `File type not allowed. Allowed types: ${options.allowedTypes.join(", ")}`;
      setError(errorMsg);
      console.error(errorMsg);
      return null;
    }

    setUploading(true);
    setError(null);
    setProgress(0);

    try {
      // Determine media type
      let mediaType = "file";
      if (file.type.startsWith("video/")) mediaType = "video";
      else if (file.type.startsWith("audio/")) mediaType = "audio";
      else if (file.type.startsWith("image/")) mediaType = "image";

      // Sanitize filename and generate unique key
      const timestamp = Date.now();
      const sanitizedName = file.name.replace(/[^a-zA-Z0-9._-]/g, "_");
      const randomSuffix = Math.random().toString(36).substring(2, 8);
      const customFileName = `${timestamp}_${randomSuffix}_${sanitizedName}`;

      const targetFolder = (uploadPath || defaultFolder) as StorageFolder;
      const key = `${targetFolder}/${customFileName}`;

      // Step 1: Get presigned URL from Convex backend
      setProgress(10);
      const { uploadUrl, fileUrl } = await generateUploadUrlAction({
        key,
        contentType: file.type || "application/octet-stream",
      });

      // Step 2: Upload directly to R2 with real progress tracking
      setProgress(15);
      await uploadToPresignedUrl(file, uploadUrl, (xhrProgress) => {
        // Map XHR progress (0-100) to our range (15-95)
        setProgress(15 + Math.round(xhrProgress * 0.8));
      });

      setProgress(100);

      const result: UploadResult = {
        url: fileUrl,
        previewUrl: fileUrl,
        storageRef: fileUrl,
        type: mediaType,
        name: file.name,
        size: file.size,
        mimeType: file.type,
      };

      setUploading(false);
      setProgress(0);

      return result;
    } catch (err: any) {
      console.error("Upload failed:", err);
      setError(err.message || "An unknown error occurred during upload.");
      setUploading(false);
      setProgress(0);
      return null;
    }
  };

  /**
   * Upload multiple files sequentially with progress tracking.
   */
  const uploadMultiple = async (
    files: FileList | File[] | null,
    uploadPath: string | null = null,
    options: UploadOptions = {}
  ): Promise<UploadResult[]> => {
    if (!files || files.length === 0) return [];

    setUploading(true);
    setError(null);
    setProgress(0);

    try {
      const fileArray = Array.from(files);
      const results: UploadResult[] = [];
      const totalFiles = fileArray.length;

      const targetFolder = (uploadPath || defaultFolder) as StorageFolder;

      for (let i = 0; i < fileArray.length; i++) {
        setProgress(Math.round(((i + 1) / totalFiles) * 100));
        const result = await uploadMedia(fileArray[i], targetFolder, options);
        if (result) {
          results.push(result);
        }
      }

      setProgress(100);
      setUploading(false);
      return results;
    } catch (err: any) {
      console.error("Batch upload failed:", err);
      setError(err.message || "Batch upload failed");
      setUploading(false);
      setProgress(0);
      return [];
    }
  };

  return {
    uploadMedia,
    uploadMultiple,
    uploading,
    error,
    progress,

    // Helpers
    isUploading: uploading,
    hasError: !!error,
    clearError: () => setError(null),
  };
}

// =====================================================
// SPECIALIZED HOOKS
// =====================================================

/**
 * Image upload hook (25MB max, image types only).
 */
export interface UseImageUploadReturn {
  uploadImage: (
    file: File | null,
    folder?: StorageFolder
  ) => Promise<UploadResult | null>;
  uploading: boolean;
  error: string | null;
  isUploading: boolean;
  hasError: boolean;
}

export function useImageUpload(options: UploadOptions = {}): UseImageUploadReturn {
  const { uploadMedia, uploading, error } = useUpload();

  const uploadImage = async (
    file: File | null,
    folder: StorageFolder = STORAGE_FOLDERS.PROFILE_PHOTOS
  ): Promise<UploadResult | null> => {
    if (!file) return null;

    if (!isImageFile(file)) {
      console.error("File is not an image");
      return null;
    }

    const imageOptions: UploadOptions = {
      maxSizeMB: UPLOAD_LIMITS.IMAGE_MAX_MB,
      allowedTypes: [...UPLOAD_LIMITS.ALLOWED_IMAGE_TYPES],
      ...options,
    };

    return await uploadMedia(file, folder, imageOptions);
  };

  return {
    uploadImage,
    uploading,
    error,
    isUploading: uploading,
    hasError: !!error,
  };
}

/**
 * Video upload hook (200MB max, video types only).
 */
export interface UseVideoUploadReturn {
  uploadVideo: (
    file: File | null,
    folder?: StorageFolder
  ) => Promise<UploadResult | null>;
  uploading: boolean;
  error: string | null;
  isUploading: boolean;
  hasError: boolean;
}

export function useVideoUpload(options: UploadOptions = {}): UseVideoUploadReturn {
  const { uploadMedia, uploading, error } = useUpload();

  const uploadVideo = async (
    file: File | null,
    folder: StorageFolder = STORAGE_FOLDERS.POST_MEDIA
  ): Promise<UploadResult | null> => {
    if (!file) return null;

    if (!isVideoFile(file)) {
      console.error("File is not a video");
      return null;
    }

    const videoOptions: UploadOptions = {
      maxSizeMB: UPLOAD_LIMITS.VIDEO_MAX_MB,
      allowedTypes: [...UPLOAD_LIMITS.ALLOWED_VIDEO_TYPES],
      ...options,
    };

    return await uploadMedia(file, folder, videoOptions);
  };

  return {
    uploadVideo,
    uploading,
    error,
    isUploading: uploading,
    hasError: !!error,
  };
}

/**
 * Audio upload hook (200MB max, audio types only).
 */
export interface UseAudioUploadReturn {
  uploadAudio: (
    file: File | null,
    folder?: StorageFolder
  ) => Promise<UploadResult | null>;
  uploading: boolean;
  error: string | null;
  isUploading: boolean;
  hasError: boolean;
}

export function useAudioUpload(options: UploadOptions = {}): UseAudioUploadReturn {
  const { uploadMedia, uploading, error } = useUpload();

  const uploadAudio = async (
    file: File | null,
    folder: StorageFolder = STORAGE_FOLDERS.POST_MEDIA
  ): Promise<UploadResult | null> => {
    if (!file) return null;

    if (!file.type.startsWith("audio/")) {
      console.error("File is not audio");
      return null;
    }

    const audioOptions: UploadOptions = {
      maxSizeMB: UPLOAD_LIMITS.AUDIO_MAX_MB,
      allowedTypes: [...UPLOAD_LIMITS.ALLOWED_AUDIO_TYPES],
      ...options,
    };

    return await uploadMedia(file, folder, audioOptions);
  };

  return {
    uploadAudio,
    uploading,
    error,
    isUploading: uploading,
    hasError: !!error,
  };
}

/**
 * Document upload hook (50MB max, document types only).
 */
export interface UseDocumentUploadReturn {
  uploadDocument: (
    file: File | null,
    folder?: StorageFolder
  ) => Promise<UploadResult | null>;
  uploading: boolean;
  error: string | null;
  isUploading: boolean;
  hasError: boolean;
}

export function useDocumentUpload(options: UploadOptions = {}): UseDocumentUploadReturn {
  const { uploadMedia, uploading, error } = useUpload();

  const uploadDocument = async (
    file: File | null,
    folder: StorageFolder = STORAGE_FOLDERS.DOCUMENTS
  ): Promise<UploadResult | null> => {
    if (!file) return null;

    const documentOptions: UploadOptions = {
      maxSizeMB: UPLOAD_LIMITS.DOCUMENT_MAX_MB,
      allowedTypes: [...UPLOAD_LIMITS.ALLOWED_DOCUMENT_TYPES],
      ...options,
    };

    return await uploadMedia(file, folder, documentOptions);
  };

  return {
    uploadDocument,
    uploading,
    error,
    isUploading: uploading,
    hasError: !!error,
  };
}

/**
 * Batch upload hook for multiple files.
 */
export interface UseBatchUploadReturn {
  uploadBatch: (
    files: FileList | File[],
    folder?: StorageFolder,
    options?: UploadOptions
  ) => Promise<UploadResult[]>;
  uploading: boolean;
  error: string | null;
  progress: number;
  isUploading: boolean;
  hasError: boolean;
}

export function useBatchUpload(): UseBatchUploadReturn {
  const { uploadMultiple, uploading, error, progress } = useUpload();

  const uploadBatch = async (
    files: FileList | File[],
    folder: StorageFolder = STORAGE_FOLDERS.POST_MEDIA,
    options: UploadOptions = {}
  ): Promise<UploadResult[]> => {
    return await uploadMultiple(files, folder, options);
  };

  return {
    uploadBatch,
    uploading,
    error,
    progress,
    isUploading: uploading,
    hasError: !!error,
  };
}

/**
 * Upload with local preview generation for images.
 */
export interface UseUploadWithPreviewReturn {
  uploadWithPreview: (
    file: File | null,
    folder?: StorageFolder
  ) => Promise<UploadResult | null>;
  preview: string | null;
  uploading: boolean;
  error: string | null;
  clearPreview: () => void;
  isUploading: boolean;
  hasError: boolean;
}

export function useUploadWithPreview(): UseUploadWithPreviewReturn {
  const [preview, setPreview] = useState<string | null>(null);
  const { uploadMedia, uploading, error } = useUpload();

  const uploadWithPreview = async (
    file: File | null,
    folder: StorageFolder = STORAGE_FOLDERS.POST_MEDIA
  ): Promise<UploadResult | null> => {
    if (!file) return null;

    // Create local preview for images
    if (isImageFile(file)) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setPreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }

    // Upload the file
    const result = await uploadMedia(file, folder);

    // Update preview with uploaded URL
    if (result) {
      setPreview(result.url);
    }

    return result;
  };

  const clearPreview = (): void => {
    setPreview(null);
  };

  return {
    uploadWithPreview,
    preview,
    uploading,
    error,
    clearPreview,
    isUploading: uploading,
    hasError: !!error,
  };
}

export default useUpload;
